### ISSUE TITLE
Create screenshots of the plugin

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Custom-Javascript-Editor#2]
To sell the plugin, we should have a couple of screenshots bundled with it:
- Show the backend with some neat Javascript
- Show the frontend with what the Javascript has done

**Comment by joshbetz** [comment]
Add in d2e3bb8

**Comment by danielbachhuber** [comment]
Did you mean to post screenshots of the CSS editor? ;)

**Comment by joshbetz** [comment]
Fixed in 6f65920
