### ISSUE TITLE
Support for third-party JS libraries

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Custom-Javascript-Editor#4]
To increase the toolset you have available to you, it would be nice to support third-party JS libraries.

This issue involves:
- Identifying the libraries we should support, and making the list filterable so it can be easily filterable
- Creating an interface on our existing editor page for selecting the libraries you'd like available on the frontend
- Enqueuing the third-party scripts on the frontend if the user wants them available.

**Comment by joshbetz** [comment]
I vote for jQuery, MooTools, and Prototype. I think it's reasonable to assume that you'd only want one at a time.

**Comment by mjangda** [comment]
We should probably support most of the ones included with WordPress core: http://codex.wordpress.org/Function_Reference/wp_enqueue_script#Default_scripts_included_with_WordPress

**Comment by joshbetz** [comment]
Good call. And I guess jQuery UI is a good example of a situation where you'd need more than one library.

**Comment by danielbachhuber** [comment]
This is nicely implemented now
