### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by joshbetz** [Automattic/Custom-Javascript-Editor#5]
Some basic syntax highlighting would be really nice.

**Comment by danielbachhuber** [comment]
@joshbetz any syntax highlighters you'd recommend?

**Comment by joshbetz** [comment]
CodeMirror - http://codemirror.net

**Comment by mjangda** [comment]
CodeMirror is probably better than ACE, which WP.com Custom CSS uses.

**Comment by danielbachhuber** [comment]
More things to add before this issue is finished:
- Allow the user to disable the syntax highligher from screen options
- Allow the user to change the theme (and possibly some basic settings) from screen options

**Comment by mjangda** [comment]
I would just wontfix those. Options are nice but probably better to keep things simple :)

**Comment by danielbachhuber** [comment]
They shouldn't be too hard to implement and I think the ability to change themes in particular is a nice touch.
